language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - ng build --prod
  - echo "Wsf10690700119" | docker login -u "2072076689465" --password-stdin
  - docker build -t 2072076689465/runrun-angular:latest .
  - docker push 2072076689465/runrun-angular:latest

